# .swiftlint.yml

# Disable specific rules
disabled_rules:
  - blanket_disable_command

# Opt-in rules
opt_in_rules:
  - attributes
  - closure_body_length
  - closure_end_indentation
  - contains_over_filter_count
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - force_cast
  - force_try
  - implicit_return
  - large_tuple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiple_closures_with_trailing_closure
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - private_outlet
  - redundant_nil_coalescing
  - single_test_class
  - sorted_first_last
  - strict_fileprivate
  - switch_case_alignment
  - toggle_bool
  - trailing_closure
  - unowned_variable_capture
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate

# Analyzer rules
analyzer_rules:
  - unused_import

# Custom rules
custom_rules:
  no_tabs:
    name: "No Tabs"
    regex: '\t'
    message: "Do not use tabs in source files."
    severity: error

# Excluded paths
# excluded:
# - /Resources/Generated